#!/bin/bash

echo Compilador archivo .pas 

java -jar Compiladores.jar potencia.pas

echo Codigo Intermedio Generado 

echo Ejecutando codigoMepa.mep en mepaV2015_64

./mepaV2015_64 codigoMEPA.mep 



